[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate"
versionNumber = "1.0.0"
description = "Custom Thunderstore modpack for Lotus Écarlate's private Valheim server. Nothing to see here, move along citizen!"
websiteUrl = "https://github.com/nbusseneau/lotus-ecarlate-valheim-modpack"
containsNsfwContent = false

[package.dependencies]
Advize-PlantEasily = "1.7.3"
Advize-PlantEverything = "1.16.5"
ASharpPen-Fall_Damage_For_Creatures = "1.1.0"
ASharpPen-Spawn_That = "1.2.10"
Azumatt-AAA_Crafting = "1.4.0"
Azumatt-AzuAreaRepair = "1.1.4"
Azumatt-AzuCraftyBoxes = "1.2.9"
Azumatt-AzuExtendedPlayerInventory = "1.3.12"
Azumatt-AzuWorkbench_Inventory_Repair = "1.0.1"
Azumatt-BowsBeforeHoes = "1.3.4"
Azumatt-ItemCompare = "1.0.2"
Azumatt-LimitWorkstationDiscovery = "1.0.1"
Azumatt-MouseTweaks = "1.0.1"
Azumatt-Queue_Me_Maybe = "1.1.1"
Azumatt-RemoveAttackFreezeFrame = "1.0.1"
Azumatt-ResourceUnloadOptimizer = "1.0.3"
Azumatt-SearchableBuildMenu = "1.0.2"
Azumatt-WardIsLove = "3.5.2"
Balrond-balrond_furRandomizer = "1.0.4"
Balrond-balrond_humanoidRandomizer = "1.3.1"
Balrond-balrond_shipyard = "1.3.7"
BentoG-MissingPieces = "2.1.0"
blacks7ar-AxeComboWhenChoppingTree = "1.0.1"
blacks7ar-ClayBuildPieces = "1.1.0"
blacks7ar-CombatOverhaulREwrite = "1.1.8"
blacks7ar-CoreWoodPieces = "1.1.6"
blacks7ar-CrystalCollector = "1.1.0"
blacks7ar-FeatherCollector = "1.1.2"
blacks7ar-FineWoodBuildPieces = "1.0.8"
blacks7ar-FollowDistance = "1.0.1"
blacks7ar-GuckCollector = "1.0.9"
blacks7ar-RegenWhileSitting = "1.0.2"
blacks7ar-RenegadeVikings = "1.2.4"
blacks7ar-ResinCollector = "1.0.8"
blacks7ar-RevampedTrader = "1.0.6"
blacks7ar-SapExtractor = "1.1.0"
blacks7ar-SNEAKer = "1.1.3"
blacks7ar-TameableLeech = "1.0.3"
blacks7ar-TarCollector = "1.1.1"
blacks7ar-VikingsDoSwim = "1.3.2"
blacks7ar-WeaponHolsterOverhaul = "1.1.2"
blacks7ar-WieldEquipmentWhileSwimming = "1.0.8"
bonesbro-FloorsAreRoofs = "2.0.2"
clevel-BeastsOfBurden = "1.0.4"
ComfyMods-Gizmo = "1.9.1"
ComfyMods-Hygge = "1.3.0"
ComfyMods-Instaloot = "1.0.0"
ComfyMods-PotteryBarn = "1.13.0"
ComfyMods-SearsCatalog = "1.4.0"
Crystal-BetterChat = "1.4.9"
Crystal-Pathfinder = "2.0.11"
Crystal-ProperPortals = "1.2.5"
Crystal-Sated = "1.1.11"
denikson-BepInExPack_Valheim = "5.4.2202"
Digitalroot-Better_Wisps = "1.0.26"
Digitalroot-Digitalroots_Slope_Combat_Assistance = "2.0.22"
DrakeMods-More_Gates_PlusPlus = "1.0.0"
Goldenrevolver-Atgeir_Polearm_Animation_Fix = "1.0.0"
Goldenrevolver-Cape_And_Torch_Resistance_Rework_And_New_Water_And_Cold_Resistance = "1.0.3"
Goldenrevolver-Harpoon_Melee_Attack_And_Upgrading = "1.0.0"
Goldenrevolver-Immersively_Obtainable_Blue_Mushrooms = "1.0.3"
Goldenrevolver-Loyal_Spears_Auto_Pickup_And_Return_To_Owner = "1.0.1"
Goldenrevolver-Obtainable_Stone_Pickaxe_and_Upgradeable_Antler_Pickaxe = "1.0.1"
Goldenrevolver-Proper_Spears_Forward_Facing_With_Thrust_Attacks = "1.0.2"
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock = "1.4.7"
Goldenrevolver-Sneak_Camera_and_Collision_Height = "1.0.2"
Goldenrevolver-Sorted_Menus_Cooking_Crafting_and_Skills_Menu = "1.3.3"
Goldenrevolver-Tree_Enemies_Are_Weak_To_Axe_Damage = "1.1.1"
Goldenrevolver-Warpick_Secondary_Pickaxe_Attack = "1.0.1"
JereKuusela-Dungeon_Splitter = "1.1.0"
JereKuusela-Render_Limits = "1.9.0"
joryjuky_team-Better_Blast_Furnaces = "1.0.0"
Korppis-SolidHitboxes = "1.0.5"
Korppis-Spearfishing = "1.0.2"
mgway-PaddlePower = "1.0.2"
MonsterLabZ-MonsterLabZ = "3.0.9"
MSchmoecker-DoorPull = "0.1.1"
MSchmoecker-FenceSnap = "0.3.0"
MSchmoecker-MultiUserChest = "0.5.10"
nbusseneau-Better_Cartography_Table = "0.3.0"
Neobotics-MaxAxe = "0.4.6"
Neobotics-Reely_SpecTackleLure = "0.2.3"
Neobotics-UnRemove = "0.1.5"
Nextek-SpeedyPaths = "1.0.8"
plumga-Clutter = "0.1.6"
Ragnar-Ragnars_Better_Autorun = "1.1.0"
RustyMods-TurfRoofs = "1.0.4"
Searica-AdvancedTerrainModifiers = "1.2.6"
Searica-DodgeShortcut = "1.1.0"
Searica-Extra_Snap_Points_Made_Easy = "1.2.4"
Searica-FortifySkillsRedux = "1.0.8"
Searica-ProjectileTweaks = "1.2.1"
Searica-ToolTweaks = "1.0.0"
shudnal-ConfigurationManager = "1.0.4"
shudnal-GammaOfNightLights = "1.0.6"
shudnal-Seasons = "1.1.9"
Smoothbrain-AntiCensorship = "1.0.2"
Smoothbrain-Backpacks = "1.3.3"
Smoothbrain-CreatureLevelAndLootControl = "4.5.20"
Smoothbrain-Groups = "1.2.7"
Smoothbrain-Guilds = "1.1.7"
Smoothbrain-Network = "1.0.2"
Smoothbrain-PackHorse = "1.0.3"
Smoothbrain-PassivePowers = "1.0.12"
Smoothbrain-Ranching = "1.1.3"
Smoothbrain-SmoothSave = "1.0.5"
Smoothbrain-StartupAccelerator = "1.0.2"
Smoothbrain-SteadyRegeneration = "1.0.2"
Smoothbrain-TargetPortal = "1.1.18"
Smoothbrain-TimedItemDestruction = "1.0.3"
Soloredis-RtDBiomes = "2.1.3"
Soloredis-RtDOcean = "1.0.6"
southsil-SouthsilArmor = "3.0.5"
Therzie-Monstrum = "1.3.8"
Therzie-Warfare = "1.6.8"
ValheimModding-Jotunn = "2.19.3"
Valphi-BetterLaddersContinued = "0.217.24"
Vapok-AutoFeedRedux = "1.0.3"
VentureValheim-Incognito_Mode = "0.3.1"
VentureValheim-Meadingful_Icons = "0.1.2"
VentureValheim-Reely_Good_Rod = "0.1.0"
VentureValheim-Venture_Logout_Tweaks = "0.5.0"
VentureValheim-Venture_Multiplayer_Tweaks = "0.11.0"
VentureValheim-World_Advancement_Progression = "0.2.11"
warpalicious-Altars_of_Creation = "1.0.2"
warpalicious-Ancient_Seed_Fertilizer = "1.0.1"
warpalicious-Blackforest_Pack_1 = "1.0.2"
warpalicious-Food_Slot_Colors = "1.0.1"
warpalicious-Meadows_Pack_1 = "1.0.2"
warpalicious-Mountains_Pack_1 = "1.0.0"
warpalicious-No_Daytime_Torches = "1.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "./config"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]

[publish.categories]
valheim = [ "modpacks", ]
