[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate"
versionNumber = "0.4.1"
description = "Custom Thunderstore modpack for Lotus Écarlate's private Valheim server. Nothing to see here, move along citizen!"
websiteUrl = "https://github.com/nbusseneau/lotus-ecarlate-valheim-modpack"
containsNsfwContent = false

[package.dependencies]
Advize-PlantEasily = "1.7.2"
ASharpPen-Spawn_That = "1.2.9"
Azumatt-AAA_Crafting = "1.3.4"
Azumatt-AzuCraftyBoxes = "1.2.5"
Azumatt-AzuWorkbench_Inventory_Repair = "1.0.1"
Crystal-Pathfinder = "2.0.11"
denikson-BepInExPack_Valheim = "5.4.2202"
Digitalroot-Digitalroots_Slope_Combat_Assistance = "2.0.22"
MSchmoecker-FenceSnap = "0.3.0"
MSchmoecker-MultiUserChest = "0.5.6"
Smoothbrain-Groups = "1.2.6"
Smoothbrain-Guilds = "1.1.6"
Smoothbrain-Network = "1.0.2"
Smoothbrain-TargetPortal = "1.1.16"
ValheimModding-Jotunn = "2.16.2"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "./config"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]

[publish.categories]
valheim = [ "modpacks", ]
