[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate"
versionNumber = "2.0.15"
description = "Custom Thunderstore modpack for Lotus Écarlate's private Valheim server. Nothing to see here, move along citizen!"
websiteUrl = "https://github.com/nbusseneau/lotus-ecarlate-valheim-modpack"
containsNsfwContent = false

[package.dependencies]
Advize-PlantEasily = "2.0.3"
Advize-PlantEverything = "1.19.1"
ASharpPen-Custom_Raids = "1.8.0"
ASharpPen-Fall_Damage_For_Creatures = "1.1.0"
ASharpPen-Spawn_That = "1.2.18"
Azumatt-AzuAreaRepair = "1.1.6"
Azumatt-AzuCraftyBoxes = "1.8.4"
Azumatt-AzuWorkbench_Inventory_Repair = "1.0.2"
Azumatt-ItemCompare = "1.0.6"
Azumatt-MouseTweaks = "1.0.2"
Azumatt-PetPantry = "1.0.5"
Azumatt-Queue_Me_Maybe = "1.1.3"
Azumatt-RemoveAttackFreezeFrame = "1.0.2"
Azumatt-SearchableBuildMenu = "1.0.4"
Azumatt-TrueInstantLootDrop = "1.0.2"
Balrond-balrond_BannerColorizer = "1.0.6"
Balrond-balrond_character_customization = "0.1.4"
Balrond-balrond_containers = "1.2.9"
Balrond-balrond_furRandomizer = "1.0.6"
Balrond-balrond_humanoidRandomizer = "1.3.8"
Balrond-balrond_shipyard = "1.5.2"
baxhax-OfficialArtLoadingScreens = "1.0.6"
BentoG-MissingPieces = "2.2.2"
blacks7ar-AxeComboWhenChoppingTree = "1.0.2"
blacks7ar-ClayBuildPieces = "1.2.5"
blacks7ar-CombatOverhaulREwrite = "1.2.5"
blacks7ar-CoreWoodPieces = "1.2.3"
blacks7ar-CrystalCollector = "1.1.6"
blacks7ar-DarkWoodFurnitures = "1.0.1"
blacks7ar-FeatherCollector = "1.1.8"
blacks7ar-FineWoodBuildPieces = "1.1.7"
blacks7ar-FineWoodFurnitures = "1.1.0"
blacks7ar-FollowDistance = "1.0.3"
blacks7ar-GuckCollector = "1.1.6"
blacks7ar-RefinedStonePieces = "1.0.9"
blacks7ar-RegenWhileSitting = "1.0.6"
blacks7ar-ResinCollector = "1.1.5"
blacks7ar-SapExtractor = "1.1.3"
blacks7ar-SNEAKer = "1.1.6"
blacks7ar-TameableLeech = "1.0.6"
blacks7ar-TarCollector = "1.1.7"
blacks7ar-VikingsDoSwim = "1.3.8"
blacks7ar-WeaponHolsterOverhaul = "1.2.0"
blacks7ar-WieldEquipmentWhileSwimming = "1.1.2"
bonesbro-FloorsAreRoofs = "2.0.2"
ComfyMods-Hygge = "1.3.1"
ComfyMods-Intermission = "1.8.0"
ComfyMods-SearsCatalog = "1.6.0"
Crystal-Pathfinder = "2.0.12"
Crystal-ProperPortals = "1.2.5"
Crystal-Sated = "1.1.11"
denikson-BepInExPack_Valheim = "5.4.2332"
Digitalroot-Better_Wisps = "1.0.42"
Digitalroot-Triple_Bronze_JVL = "1.1.52"
flashybaps-BeastsOfBurdenEV = "1.0.5"
GetOffMyLawn-ToggleMovementMod = "1.4.2"
glawks-BetterNetworking_Valheim = "2.3.2"
Goldenrevolver-Atgeir_Polearm_Animation_Fix = "1.0.0"
Goldenrevolver-Cape_And_Torch_Resistance_Rework_And_New_Water_And_Cold_Resistance = "1.0.4"
Goldenrevolver-Harpoon_Melee_Attack_And_Upgrading = "1.0.1"
Goldenrevolver-Immersively_Obtainable_Blue_Mushrooms = "1.0.3"
Goldenrevolver-Loyal_Spears_Auto_Pickup_And_Return_To_Owner = "1.2.0"
Goldenrevolver-Obtainable_Stone_Pickaxe_and_Upgradeable_Antler_Pickaxe = "1.0.1"
Goldenrevolver-Proper_Spears_Forward_Facing_With_Thrust_Attacks = "1.0.3"
Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock = "1.4.13"
Goldenrevolver-Sneak_Camera_and_Collision_Height = "1.0.2"
Goldenrevolver-Tree_Enemies_Are_Weak_To_Axe_Damage = "1.1.2"
Goldenrevolver-Warpick_Secondary_Pickaxe_Attack = "1.0.2"
JereKuusela-Dungeon_Splitter = "1.7.0"
JereKuusela-Projectile_Collision = "1.7.0"
JereKuusela-Render_Limits = "1.13.0"
JereKuusela-Smoke_Collision = "1.9.0"
joryjuky_team-Better_Blast_Furnaces = "1.0.0"
Korppis-Spearfishing = "1.0.4"
Lotus_Ecarlate-Lotus_Ecarlate_Changes = "0.7.6"
Mayo-MorDoor = "2.1.0"
MSchmoecker-DoorPull = "0.1.1"
MSchmoecker-FenceSnap = "0.3.0"
MSchmoecker-MultiUserChest = "0.6.1"
MSchmoecker-TimeoutLimit = "0.2.0"
MySoloTeam-IngotStacks = "1.0.2"
nbusseneau-Better_Cartography_Table = "0.8.1"
nbusseneau-Fuel_Daylight_Saving = "0.4.1"
Neobotics-BetterStakes = "0.1.1"
Neobotics-MaxAxe = "0.5.7"
Neobotics-Reely_SpecTackleLure = "0.2.4"
Nextek-SpeedyPaths = "1.0.8"
plumga-Clutter = "0.1.7"
Riintouge-LongerPetNames = "1.0.1"
Searica-AdvancedTerrainModifiers = "1.4.1"
Searica-FortifySkillsRedux = "1.5.3"
Searica-More_Vanilla_Build_Prefabs = "1.4.4"
Searica-ProjectileTweaks = "1.6.0"
Searica-ToolTweaks = "1.2.1"
shudnal-BuyDvergrExtractorNeedle = "1.0.3"
shudnal-ConfigurationManager = "1.1.5"
shudnal-ExtraSlots = "1.0.32"
shudnal-MoreGatesExtended = "1.0.2"
shudnal-ProtectiveWards = "1.2.7"
shudnal-RockTheBoat = "1.0.10"
shudnal-Seasons = "1.6.4"
Smoothbrain-AntiCensorship = "1.0.2"
Smoothbrain-CombatOwner = "1.0.0"
Smoothbrain-CreatureLevelAndLootControl = "4.6.4"
Smoothbrain-Groups = "1.2.9"
Smoothbrain-Guilds = "1.1.11"
Smoothbrain-PackHorse = "1.0.3"
Smoothbrain-PassivePowers = "1.1.2"
Smoothbrain-Ranching = "1.1.3"
Smoothbrain-SmoothSave = "1.0.5"
Smoothbrain-StartupAccelerator = "1.0.3"
Smoothbrain-SteadyRegeneration = "1.0.3"
Smoothbrain-TargetPortal = "1.2.0"
Smoothbrain-TimedItemDestruction = "1.0.3"
Soloredis-RtDBiomes = "2.9.1"
southsil-SouthsilArmor = "3.1.7"
Therzie-Monstrum = "1.5.1"
Therzie-Warfare = "1.8.9"
ValheimModding-Jotunn = "2.26.0"
ValheimModding-JsonDotNET = "13.0.4"
ValheimModding-YamlDotNet = "16.3.1"
Valphi-BetterLaddersContinued = "0.217.24"
VentureValheim-Meadingful_Icons = "0.2.0"
VentureValheim-Reely_Good_Rod = "0.1.1"
VentureValheim-Venture_Logout_Tweaks = "0.6.0"
VentureValheim-Venture_Multiplayer_Tweaks = "0.11.7"
VentureValheim-World_Advancement_Progression = "0.3.6"
Vismeneer-MoreMissingPieces = "1.1.0"
warpalicious-Monster_Modifiers = "1.2.6"
warpalicious-More_World_Locations_AIO = "1.1.0"
ZenDragon-Zen_ModLib = "1.2.3"
ZenDragon-ZenBossStone = "0.3.0"
ZenDragon-ZenCombat = "0.5.0"
ZenDragon-ZenConstruction = "0.5.1"
ZenDragon-ZenHoverItem = "0.4.0"
ZenDragon-ZenItemStands = "0.6.0"
ZenDragon-ZenPlayer = "0.4.0"
ZenDragon-ZenRecycle = "0.4.0"
ZenDragon-ZenRedecorate = "1.2.0"
ZenDragon-ZenSign = "1.3.1"
ZenDragon-ZenUI = "0.6.1"
ZenDragon-ZenUseItem = "0.3.2"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./config"
target = "./config"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]

[publish.categories]
valheim = [ "modpacks", ]
