timezone: Europe/Paris
interval: 60
jobs:
  # Generic cleanup: every day
  - command: clean_chests
    schedule: "30 4 * * *"
  - command: clean_dungeons
    schedule: "30 4 * * *"
  - command: clean_locations
    schedule: "30 4 * * *"
  - command: clean_objects
    schedule: "30 4 * * *"
  - command: clean_stands
    schedule: "30 4 * * *"
  - command: start
    schedule: "31 4 * * *"

  # Reboot: every day
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 15 MINUTES</color>
    schedule: "30 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 10 MINUTES</color>
    schedule: "35 4 * * *"
  - command: save # early saves just in case
    schedule: "40 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 5 MINUTES - DÉCONNECTEZ-VOUS BIENTÔT</color>
    schedule: "40 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 4 MINUTES - DÉCONNECTEZ-VOUS BIENTÔT</color>
    schedule: "41 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 3 MINUTES - DÉCONNECTEZ-VOUS BIENTÔT</color>
    schedule: "42 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 2 MINUTES - DÉCONNECTEZ-VOUS IMMÉDIATEMENT</color>
    schedule: "43 4 * * *"
  - command: save # early saves just in case
    schedule: "43 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 1 MINUTE - DÉCONNECTEZ-VOUS IMMÉDIATEMENT</color>
    schedule: "44 4 * * *"
  - command: save # actual reboot done via system cron
    schedule: "44 4 * * *"

  # Resetting Hildir and Dyrnwyn locations: every Monday, forced even if player structures nearby
  - command: locations_reset Hildir_crypt,Hildir_cave,Hildir_plainsfortress,PlaceofMystery1,PlaceofMystery2,PlaceofMystery3 force start
    schedule: "15 5 * * 1"

  # Resetting inner ring around spawn things: 25% locations every day (5 days rotation)
  - command: locations_reset chance=25 pos=129,-191 min=30 max=1000 # distance safeguard for start temple, use `find StartTemple` to get position
    schedule: "15 5 * * *"
  # Resetting important things: 5% locations every day (20 days rotation), 20% of one type of vegetation every 4 days (20 days rotation)
  - command: locations_reset chance=5 pos=129,-191 min=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset rock4_copper terrain=30 chance=20
    schedule: "15 5 * * 1/4"
  - command: vegetation_reset MineRock_Tin terrain=2 chance=20
    schedule: "15 5 * * 2/4"
  - command: vegetation_reset silvervein terrain=50 chance=20
    schedule: "15 5 * * 3/4"
  - command: vegetation_reset Leviathan,Pickable_SeedCarrot,Pickable_SeedTurnip chance=20
    schedule: "15 5 * * 4/4"
  - command: start
    schedule: "16 5 * * *"
zone: []
join: []
logJobs: true
logZone: true
logJoin: true
discordConnector: false
