timezone: Europe/Paris
interval: 900
jobs:
  # Generic cleanup: every day
  - command: clean_chests
    schedule: "30 4 * * *"
  - command: clean_dungeons
    schedule: "30 4 * * *"
  - command: clean_locations
    schedule: "30 4 * * *"
  - command: clean_objects
    schedule: "30 4 * * *"
  - command: clean_stands
    schedule: "30 4 * * *"
  - command: start
    schedule: "31 4 * * *"

  # Reboot: every day
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 15 MINUTES</color>
    schedule: "30 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 10 MINUTES</color>
    schedule: "35 4 * * *"
  - command: save # early save just in case
    schedule: "40 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 5 MINUTES - DÉCONNECTEZ-VOUS BIENTÔT</color>
    schedule: "40 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 4 MINUTES - DÉCONNECTEZ-VOUS BIENTÔT</color>
    schedule: "41 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 3 MINUTES - DÉCONNECTEZ-VOUS BIENTÔT</color>
    schedule: "42 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 2 MINUTES - DÉCONNECTEZ-VOUS IMMÉDIATEMENT</color>
    schedule: "43 4 * * *"
  - command: broadcast center <color=orange>REBOOT DU SERVEUR DANS 1 MINUTE - DÉCONNECTEZ-VOUS IMMÉDIATEMENT</color>
    schedule: "44 4 * * *"
  - command: save # actual reboot done via system cron
    schedule: "45 4 * * *"

  # Resetting important things
  ## Around spawn: 25% every day (4 days rotation)
  - command: chests_reset looted chance=25 pos=0,0 min=30 max=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset rock4_copper,mudpile_beacon terrain=30 chance=25 pos=0,0 min=30 max=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset MineRock_Tin,Pickable_SeedTurnip,Pickable_SeedCarrot,BFP_Pickable_Clay,BFP_Pickable_ClayBig terrain=2 chance=25 pos=0,0 min=30 max=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset silvervein terrain=50 chance=25 pos=0,0 min=30 max=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset Leviathan chance=25 pos=0,0 min=30 max=1000
    schedule: "15 5 * * *"
  - command: locations_reset chance=25 pos=0,0 min=30 max=1000
    schedule: "15 5 * * *"

  ## Further away from spawn: 5% every day (20 days rotation)
  - command: chests_reset looted chance=5 pos=0,0 min=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset rock4_copper,mudpile_beacon terrain=30 chance=5 pos=0,0 min=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset MineRock_Tin,Pickable_SeedTurnip,Pickable_SeedCarrot,BFP_Pickable_Clay,BFP_Pickable_ClayBig terrain=2 chance=5 pos=0,0 min=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset silvervein terrain=50 chance=5 pos=0,0 min=1000
    schedule: "15 5 * * *"
  - command: vegetation_reset Leviathan chance=5 pos=0,0 min=1000
    schedule: "15 5 * * *"
  - command: locations_reset chance=5 pos=0,0 min=1000
    schedule: "15 5 * * *"

  ## Hildir dungeons: every Monday
  - command: locations_reset Hildir_crypt,Hildir_cave,Hildir_plainsfortress
    schedule: "15 5 * * 1"

  ## Execute
  - command: start
    schedule: "16 5 * * *"
zone: []
join: []
logJobs: true
logZone: true
logJoin: true
discordConnector: false
