timezone: Europe/Paris
interval: 900
jobs:
  # Around spawn: reset 25% every day (4 days rotation)
  - command: chests_reset looted chance=25 pos=0,0 min=30 max=1000 start
    schedule: "20 6 * * *"

  - command: vegetation_reset rock4_copper,mudpile_beacon terrain=30 chance=25 pos=0,0 min=30 max=1000 start
    schedule: "30 6 * * *"

  - command: vegetation_reset MineRock_Tin,Pickable_SeedTurnip,Pickable_SeedCarrot,BFP_Pickable_Clay,BFP_Pickable_ClayBig terrain=2 chance=25 pos=0,0 min=30 max=1000 start
    schedule: "40 6 * * *"

  - command: vegetation_reset silvervein terrain=50 chance=25 pos=0,0 min=30 max=1000 start
    schedule: "50 6 * * *"

  - command: vegetation_reset Leviathan chance=25 pos=0,0 min=30 max=1000 start
    schedule: "0 7 * * *"

  - command: locations_reset chance=25 pos=0,0 min=30 max=1000 start
    schedule: "10 7 * * *"

  # Further away: reset 10% every 2 days (20 days rotation)
  - command: chests_reset looted chance=10 pos=0,0 min=1000 start
    schedule: "0 5 */2 * *"

  - command: vegetation_reset rock4_copper,mudpile_beacon terrain=30 chance=10 pos=0,0 min=1000 start
    schedule: "10 5 */2 * *"

  - command: vegetation_reset MineRock_Tin,Pickable_SeedTurnip,Pickable_SeedCarrot,BFP_Pickable_Clay,BFP_Pickable_ClayBig terrain=2 chance=10 pos=0,0 min=1000 start
    schedule: "20 5 */2 * *"

  - command: vegetation_reset silvervein terrain=50 chance=10 pos=0,0 min=1000 start
    schedule: "30 5 */2 * *"

  - command: vegetation_reset Leviathan chance=10 pos=0,0 min=1000 start
    schedule: "40 5 */2 * *"

  - command: locations_reset chance=10 pos=0,0 min=1000 start
    schedule: "50 5 */2 * *"
zone: []
join: []
logJobs: true
logZone: true
logJoin: true
discordConnector: false
